### PR TITLE
Update README with quickstart instructions

### PR DESCRIPTION
**Pull request by madig**
Courtesy of you ;)

### CODE REVIEW

**Comment by m4rc1e** [comment]
Hahah thanks!

So I take it you've got it running locally?

It would be interesting to sit down with you, @davelab6, @graphicore to layout a roadmap which would benefit us all.

**Comment by davelab6** [comment]
@m4rc1e shouldn't you merge and update the docs? :)

**Comment by m4rc1e** [comment]
Sure. We'll need to update this once spinning up your own instance is less painful.

I'm looking forward to meeting you @madig

**Comment by madig** [comment]
No worky...

**Comment by madig** [comment]
This is weird. The key doesn't seem to be on the server?!

http://keys.gnupg.net/pks/lookup?search=3B87619DF812A63A8C1005C30742918E5C8DA04A&hash=on&op=hget

**Comment by madig** [comment]
Next problem: on what port does the thing listen...

**Comment by m4rc1e** [comment]
try `docker-machine ls`

**Pull request merged**
