### PR TITLE
contenteditable and fixed install link

### PR DESCRIPTION
**Pull request by alexeiva**

### CODE REVIEW

**Comment by m4rc1e** [comment]
@alexeiva sorry for the delay in looking at this.

A couple of things:
-Squash the Update README.md prs
-Currently, the right column is content editable. The left column is not
screen shot 2016-11-28 at 13 07 45

Otherwise, I'm cool with this. Good job.

**Comment by m4rc1e** [comment]
Bang! thank you!

**Comment by alexeiva** [comment]
bing! Next up I am working on this:

screen shot 2016-11-28 at 2 35 53 pm

Your script only fetches the Latin range from the GF servers. I cannot compare the new and old Cyrillic. Sad story. Is this an easy fix?

**Comment by m4rc1e** [comment]
This test was just for the vertical metrics.

I'd prefer to do this sort of testing in a new page called languages.

**Comment by m4rc1e** [comment]
You have to intelligently find the language as well. nothing here is arbitrary like Impallari/testing.

**Comment by alexeiva** [comment]
I can't properly set v metrics without regards to other scripts.

For just checking if the v metrics diverge from sources Latin will suffice.

So, languages tab is a good idea

**Comment by m4rc1e** [comment]
Yes you can.

Your vertical metrics should not be based on Vietnamese or any scripts. We use the Latin script to establish the appearance of our vertical metrics. If people need Vietnamese or other tall scripts without collisions, they'll have to adjust the leading/line-height.

Read the mega thread on our Google discussion [Khaled's proposed vertical metrics setup](https://groups.google.com/d/msg/googlefonts-discuss/W4PHxnLk3JY/2Xrk9KgkAwAJ). We've favoured Khaled's approach on old fonts and Kalapi's for new fonts.

**Pull request merged**
