### PR TITLE
[models] Support fonts with filenames that do not specify a style.

### LINKED ISSUE #15: Hangs indefinitely when uploading 2 local fonts
"Comparing two sets of local fonts" on http://45.55.138.144/, dragging in two fonts and clicking upload makes the site hang...

### PR DESCRIPTION
**Pull request by m4rc1e**
Fixes #15

@madig this should roll into production after lunch. 

I'm more than happy to get you up and running on your own local version if you'd like?

### CODE REVIEW

**Comment by madig** [comment]
Yes! I was about to file an issue asking how to start the damn thing locally, but then I found docker-rebuild.sh and now I'm fluffing about.

I have some specific workflow involving a GitLab CI pipeline in mind, but that's after I explored a bit more. I suppose you'll be a TypoLabs?

**Comment by m4rc1e** [comment]
@madig Yeah, I'll be at TypoLabs.

A quick way to get this off the ground

```
# Create a new docker machine
docker-machine create gf-regression

# Run the machine
docker-machine start gf-regression

# log into machine
docker-machine env gf-regression (copy n paste returned command)

# build and run using docker-compose (make sure you have your Python virtualenv enabled and you're in the parent dir
docker-compose up

```

Building the imgs and containers may take a while

**Comment by m4rc1e** [comment]
@madig if you have no objections to this pr, I'll give it a merge and get it online asap.

**Comment by madig** [comment]
No objections :) Might be better to one day extract the family and style name from the font itself, but it'll do for now.

**Pull request merged**
